/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as BlogQualityLaboratoryRouteImport } from './routes/blog.quality-laboratory'
import { Route as BlogExportLogisticsRouteImport } from './routes/blog.export-logistics'
import { Route as BlogCircularEconomyRouteImport } from './routes/blog.circular-economy'
import { Route as BlogBoppLaminationRouteImport } from './routes/blog.bopp-lamination'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogQualityLaboratoryRoute = BlogQualityLaboratoryRouteImport.update({
  id: '/quality-laboratory',
  path: '/quality-laboratory',
  getParentRoute: () => BlogRoute,
} as any)
const BlogExportLogisticsRoute = BlogExportLogisticsRouteImport.update({
  id: '/export-logistics',
  path: '/export-logistics',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCircularEconomyRoute = BlogCircularEconomyRouteImport.update({
  id: '/circular-economy',
  path: '/circular-economy',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBoppLaminationRoute = BlogBoppLaminationRouteImport.update({
  id: '/bopp-lamination',
  path: '/bopp-lamination',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/sitemap': typeof SitemapRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/blog/bopp-lamination': typeof BlogBoppLaminationRoute
  '/blog/circular-economy': typeof BlogCircularEconomyRoute
  '/blog/export-logistics': typeof BlogExportLogisticsRoute
  '/blog/quality-laboratory': typeof BlogQualityLaboratoryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/sitemap': typeof SitemapRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/blog/bopp-lamination': typeof BlogBoppLaminationRoute
  '/blog/circular-economy': typeof BlogCircularEconomyRoute
  '/blog/export-logistics': typeof BlogExportLogisticsRoute
  '/blog/quality-laboratory': typeof BlogQualityLaboratoryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRoute
  '/manufacturing': typeof ManufacturingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/sitemap': typeof SitemapRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/blog/bopp-lamination': typeof BlogBoppLaminationRoute
  '/blog/circular-economy': typeof BlogCircularEconomyRoute
  '/blog/export-logistics': typeof BlogExportLogisticsRoute
  '/blog/quality-laboratory': typeof BlogQualityLaboratoryRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/sitemap'
    | '/sustainability'
    | '/terms'
    | '/blog/bopp-lamination'
    | '/blog/circular-economy'
    | '/blog/export-logistics'
    | '/blog/quality-laboratory'
    | '/products/$slug'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/sitemap'
    | '/sustainability'
    | '/terms'
    | '/blog/bopp-lamination'
    | '/blog/circular-economy'
    | '/blog/export-logistics'
    | '/blog/quality-laboratory'
    | '/products/$slug'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/manufacturing'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/sitemap'
    | '/sustainability'
    | '/terms'
    | '/blog/bopp-lamination'
    | '/blog/circular-economy'
    | '/blog/export-logistics'
    | '/blog/quality-laboratory'
    | '/products_/$slug'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareerRoute: typeof CareerRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  IndustriesRoute: typeof IndustriesRoute
  ManufacturingRoute: typeof ManufacturingRoute
  PrivacyRoute: typeof PrivacyRoute
  QualityRoute: typeof QualityRoute
  QuoteRoute: typeof QuoteRoute
  SitemapRoute: typeof SitemapRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/quality-laboratory': {
      id: '/blog/quality-laboratory'
      path: '/quality-laboratory'
      fullPath: '/blog/quality-laboratory'
      preLoaderRoute: typeof BlogQualityLaboratoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/export-logistics': {
      id: '/blog/export-logistics'
      path: '/export-logistics'
      fullPath: '/blog/export-logistics'
      preLoaderRoute: typeof BlogExportLogisticsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/circular-economy': {
      id: '/blog/circular-economy'
      path: '/circular-economy'
      fullPath: '/blog/circular-economy'
      preLoaderRoute: typeof BlogCircularEconomyRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/bopp-lamination': {
      id: '/blog/bopp-lamination'
      path: '/bopp-lamination'
      fullPath: '/blog/bopp-lamination'
      preLoaderRoute: typeof BlogBoppLaminationRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogBoppLaminationRoute: typeof BlogBoppLaminationRoute
  BlogCircularEconomyRoute: typeof BlogCircularEconomyRoute
  BlogExportLogisticsRoute: typeof BlogExportLogisticsRoute
  BlogQualityLaboratoryRoute: typeof BlogQualityLaboratoryRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBoppLaminationRoute: BlogBoppLaminationRoute,
  BlogCircularEconomyRoute: BlogCircularEconomyRoute,
  BlogExportLogisticsRoute: BlogExportLogisticsRoute,
  BlogQualityLaboratoryRoute: BlogQualityLaboratoryRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareerRoute: CareerRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  IndustriesRoute: IndustriesRoute,
  ManufacturingRoute: ManufacturingRoute,
  PrivacyRoute: PrivacyRoute,
  QualityRoute: QualityRoute,
  QuoteRoute: QuoteRoute,
  SitemapRoute: SitemapRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
